Repository Lovely-4K/love-frontend, pull requests merged in 2023-12, with the labels that each got.

#151 ✨ Feat: 다이어리 수정 API 반영
  src/pages/Diary/components/DiaryMain/DiaryMain.tsx
  src/pages/Diary/components/DiaryMain/DiaryMainLoadingFallback.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecords.tsx
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/types/diary.ts
Labels: ✨ Feat

#159 💄 Style: 사이드바 반응형 처리
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
Labels: 💄 Style, 🔨 Refactoring

#162 🔨 Refactor: Couple 상태에 따른 분기 처리
  src/contexts/LayoutContext.tsx
  src/contexts/index.ts
  src/hooks/useLayoutContext.ts
  src/pages/Main/components/MainContent/MainContent.tsx
  src/pages/Main/components/MainModalButtons/MainModalButtons.tsx
  src/pages/Main/components/MainProfile/MainProfile.tsx
  src/pages/Main/components/MainProfileModal/ProfileBirthdayItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileColorItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileContainer.tsx
  src/pages/Main/components/MainProfileModal/ProfileMBTIItem.tsx
  src/pages/Main/contexts/MainContentContext.tsx
  src/pages/Main/contexts/MainContext.tsx
  src/pages/Main/contexts/ProfileModalContext.tsx
  src/pages/Setting/components/SettingContent/SettingContent.tsx
  src/pages/Setting/components/SettingTab.tsx
  src/pages/Setting/constants/settingTab.ts
  src/router/Layout.tsx
  src/router/LayoutWithCouple.tsx
  src/router/router.tsx
  src/services/couple/useGetCoupleProfile.ts
  src/types/couple.ts
Labels: 🔨 Refactoring

#164 🚨 Fix: 다이어리 지도 초기 위치 설정
  src/pages/Diary/components/DiaryMap/DiaryMap.tsx
  src/pages/Diary/hooks/Diary/useCurrentLocation.ts
Labels: 🚨 Fix

#166 ✨ Feat | Toast UI 추가
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainProfileModal/ProfileContainer.tsx
  src/pages/Main/components/MainProfileModal/ProfileMBTIItem.tsx
  src/pages/Main/contexts/ProfileModalContext.tsx
  src/router/LayoutWithCouple.tsx
Labels: ✨ Feat

#168 ✨ Feat: Recouple Modal 추가
  src/contexts/LayoutContext.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainContent/MainContent.tsx
  src/pages/Main/components/MainModalButtons/MainModalButtons.tsx
  src/pages/Main/components/MainProfile/MainProfile.tsx
  src/pages/Main/contexts/MainContentContext.tsx
  src/pages/Setting/components/SettingContent/SettingContent.tsx
  src/pages/Setting/components/SettingTab.tsx
  src/router/LayoutWithCouple.tsx
Labels: ✨ Feat

#174 🔨 Refactor: Calendar Page Context 상태 관리 제거 및 Jotai로 전환
  src/components/domain/ScheduleItem/ScheduleItem.tsx
  src/pages/Calendar/Calendar.tsx
  src/pages/Calendar/components/CalendarMain/CalendarMain.tsx
  src/pages/Calendar/components/CalendarMain/ScheduleDots.tsx
  src/pages/Calendar/components/CalendarSideBar/CalendarSideBar.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarDaySchedule.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/EditDate.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/EditInput.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/EditOwner.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/EditType.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/SideBarEditSchedule.tsx
  src/pages/Calendar/contexts/CalendarContext.tsx
  src/pages/Calendar/contexts/CalendarMainContext.tsx
  src/pages/Calendar/contexts/CalendarSideBarContext.tsx
  src/pages/Calendar/contexts/index.ts
  src/pages/Calendar/hooks/index.ts
  src/pages/Calendar/hooks/useCalendar.ts
  src/pages/Calendar/hooks/useCalendarMain.ts
  src/pages/Calendar/hooks/useCalendarSideBar.ts
  src/pages/Calendar/stores/calendarAtom.ts
  src/pages/Calendar/utils/getDaySchedules.ts
  src/pages/Calendar/utils/index.ts
  src/types/calendar.ts
Labels: 🔨 Refactoring
