Repository Lovely-4K/love-frontend, pull requests merged in 2023-11, with the labels that each got.

#63 ✨ Feat: Question Page 구현
  src/assets/icons/close.svg
  src/assets/icons/imageAdd.svg
  src/assets/icons/index.ts
  src/assets/icons/leftArrow.svg
  src/assets/icons/menu.svg
  src/assets/icons/plus.svg
  src/components/common/CategoryButton/CategoryButton.tsx
  src/components/common/CategoryButton/CategoryIcon.ts
  src/components/common/CircleButton/CircleButton.tsx
  src/components/common/CircleButton/index.ts
  src/components/common/index.ts
  src/components/domain/NavigationHeader/NavigationHeader.tsx
  src/components/domain/NavigationHeader/index.ts
  src/components/domain/index.ts
  src/pages/Question/Question.tsx
  src/pages/Question/components/QuestionChat/QuestionChat.tsx
  src/pages/Question/components/QuestionChat/QuestionChatItem.tsx
  src/pages/Question/components/QuestionChat/index.ts
  src/pages/Question/components/QuestionForm/QuestionForm.tsx
  src/pages/Question/components/QuestionForm/QuestionFormCreate.tsx
  src/pages/Question/components/QuestionForm/QuestionFormLabel.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelect.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelectItem.tsx
  src/pages/Question/components/QuestionForm/index.ts
  src/pages/Question/components/QuestionHeader/QuestionHeader.tsx
  src/pages/Question/components/QuestionHeader/index.ts
  src/pages/Question/components/index.ts
  src/pages/Question/index.ts
  src/pages/QuestionCreate/QuestionCreate.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/Form.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswer.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswerCard.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswerInput.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormQuestion.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/index.ts
  src/pages/QuestionCreate/components/QuestionCreateHeader.tsx
  src/pages/QuestionCreate/components/index.ts
  src/pages/QuestionCreate/contexts/QuestionCreateFormContext.tsx
  src/pages/QuestionCreate/hooks/useQuestionCreateForm.tsx
  src/pages/QuestionCreate/index.ts
  src/pages/QuestionHistory/QuestionHistory.tsx
  src/pages/QuestionHistory/components/HistoryHeader.tsx
  src/pages/QuestionHistory/components/HistoryList/HistoryItem.tsx
  src/pages/QuestionHistory/components/HistoryList/HistoryList.tsx
  src/pages/QuestionHistory/components/HistoryList/index.ts
  src/pages/QuestionHistory/components/index.ts
  src/pages/QuestionHistory/index.ts
  src/pages/index.ts
  src/router/Router.tsx
  src/theme/avatar.ts
  src/theme/font.ts
Labels: ✨ Feat

#68 ✨ Feat: Diary 페이지 UI 구현
  src/assets/icons/imageGallery.svg
  src/assets/icons/index.ts
  src/assets/icons/search.svg
  src/assets/icons/topArrow.svg
  src/components/domain/Carousel/Carousel.tsx
  src/components/domain/Footer/Footer.tsx
  src/components/domain/Rating/Rating.tsx
  src/pages/Diary/Diary.tsx
  src/pages/Diary/components/DiaryCommon/DiaryCategoryList.tsx
  src/pages/Diary/components/DiaryCommon/DiaryHeader.tsx
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
  src/pages/Diary/components/DiaryCommon/index.ts
  src/pages/Diary/components/DiaryContent/DiaryContent.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentDate.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentImgs.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentRating.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentText.tsx
  src/pages/Diary/components/DiaryContent/index.ts
  src/pages/Diary/components/DiaryContentLists/DiaryContentLists.tsx
  src/pages/Diary/components/DiaryContentLists/DiaryItems.tsx
  src/pages/Diary/components/DiaryContentLists/DiaryNotContent.tsx
  src/pages/Diary/components/DiaryContentLists/index.ts
  src/pages/Diary/components/DiaryMain/DiaryMain.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecords.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchBar.tsx
  src/pages/Diary/components/DiaryMain/index.ts
  src/pages/Diary/index.ts
  src/router/Router.tsx
Labels: ✨ Feat

#73 ✨ Feat: member, question 관련 api 반환 타입 추가
  .eslintrc.cjs
  src/types/index.ts
  src/types/member.ts
  src/types/question.ts
Labels: ✨ Feat

#74 ✨ Feat: couple, diary 응답 값 type 추가
  src/types/couple.ts
  src/types/diary.ts
Labels: ✨ Feat

#79 ✨ Feature: QuestionCreate 페이지 API 함수 구현 & 카카오 지도 불러오기 구현
  index.html
  package-lock.json
  package.json
  src/components/common/CategoryButton/CategoryButton.tsx
  src/components/domain/Footer/Footer.tsx
  src/pages/Diary/Diary.tsx
  src/pages/Diary/components/DiaryCommon/DiaryCategoryList.tsx
  src/pages/Diary/components/DiaryCommon/DiaryHeader.tsx
  src/pages/Diary/components/DiaryContent/DiaryContent.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentRating.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/Form.tsx
  src/pages/QuestionCreate/components/QuestionCreateHeader.tsx
  src/pages/QuestionCreate/hooks/useCreateForm.ts
  src/pages/QuestionCreate/hooks/useQuestionCreateForm.tsx
  src/pages/QuestionHistory/components/HistoryHeader.tsx
  src/router/paths.ts
  src/types/common.ts
  src/types/index.ts
  src/types/question.ts
  tsconfig.json
Labels: ✨ Feat

#81 ✨ Feat: 질문 페이지 api 연동 테스트
  src/pages/Question/components/QuestionChat/QuestionChat.tsx
  src/pages/Question/components/QuestionChat/QuestionChatItem.tsx
  src/pages/Question/components/QuestionForm/QuestionForm.tsx
  src/pages/Question/components/QuestionForm/QuestionFormLabel.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelect.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelectItem.tsx
  src/pages/Question/components/QuestionHeader/QuestionHeader.tsx
  src/pages/Question/contexts/QuestionContext.tsx
  src/pages/Question/hooks/useCreateTodayQuestion.ts
  src/pages/Question/hooks/useGetQuestion.ts
  src/pages/Question/hooks/usePatchAnswerQuestion.ts
  src/pages/Question/hooks/useQuestionForm.tsx
  src/pages/Question/hooks/useUpdateUserAnswer.ts
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswer.tsx
  src/pages/QuestionCreate/hooks/useCreateForm.ts
  src/pages/QuestionCreate/hooks/useQuestionCreateForm.tsx
  src/pages/QuestionHistory/components/HistoryList/HistoryItem.tsx
  src/pages/QuestionHistory/components/HistoryList/HistoryList.tsx
  src/pages/QuestionHistory/hooks/useGetQuestionDetail.ts
  src/pages/QuestionHistory/hooks/useGetQuestions.ts
  src/types/question.ts
Labels: ✨ Feat

#90 🚨HotFix: 질문 페이지 백엔드 API 연동
  src/pages/Question/Question.tsx
  src/pages/Question/components/QuestionChat/QuestionChat.tsx
  src/pages/Question/components/QuestionChat/QuestionChatItem.tsx
  src/pages/Question/components/QuestionForm/QuestionForm.tsx
  src/pages/Question/components/QuestionForm/QuestionFormLabel.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelect.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelectItem.tsx
  src/pages/Question/components/QuestionHeader/QuestionHeader.tsx
  src/pages/Question/contexts/QuestionContext.tsx
  src/pages/Question/hooks/useCreateTodayQuestion.ts
  src/pages/Question/hooks/useGetQuestion.ts
  src/pages/Question/hooks/useQuestion.tsx
  src/pages/Question/hooks/useQuestionForm.tsx
  src/pages/Question/hooks/useUpdateUserAnswer.ts
  src/pages/QuestionCreate/hooks/useCreateForm.ts
  src/pages/QuestionHistory/components/HistoryList/HistoryItem.tsx
  src/pages/QuestionHistory/hooks/useGetQuestionDetail.ts
  src/types/question.ts
Labels: 🚨 Fix

#86 ✨ Feat: mainpage api 연결작업
  src/components/common/Avatar/Avatar.tsx
  src/components/common/index.ts
  src/components/domain/IsNotCoupleModal/NotCoupleModal.tsx
  src/components/domain/Modal/Modal.tsx
  src/components/domain/Modal/index.ts
  src/components/domain/index.ts
  src/hooks/useModal.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainContent/InviteContainer.tsx
  src/pages/Main/components/MainContent/MainContent.tsx
  src/pages/Main/components/MainContent/PreviewCalendar.tsx
  src/pages/Main/components/MainContent/PreviewDiary.tsx
  src/pages/Main/components/MainContent/PreviewItem.tsx
  src/pages/Main/components/MainContent/PreviewNoneItem.tsx
  src/pages/Main/components/MainContent/PreviewQuestion.tsx
  src/pages/Main/components/MainContent/PreviewsContainer.tsx
  src/pages/Main/components/MainContent/index.ts
  src/pages/Main/components/MainCouple.tsx
  src/pages/Main/components/MainDdayModal/DdayContainer.tsx
  src/pages/Main/components/MainDdayModal/MainDdayModal.tsx
  src/pages/Main/components/MainInviteModal/InviterProfile.tsx
  src/pages/Main/components/MainInviteModal/MainInviteModal.tsx
  src/pages/Main/components/MainModalButtons/MainModalButtons.tsx
  src/pages/Main/components/MainPreviews/MainPreviews.tsx
  src/pages/Main/components/MainPreviews/index.ts
  src/pages/Main/components/MainProfile/CoupleProfile.tsx
  src/pages/Main/components/MainProfile/MainCoupleProfile.tsx
  src/pages/Main/components/MainProfile/MainProfile.tsx
  src/pages/Main/components/MainProfile/Profile.tsx
  src/pages/Main/components/MainProfile/SoloProfile.tsx
  src/pages/Main/components/MainProfile/index.ts
  src/pages/Main/components/MainProfileModal/MBTIButton.tsx
  src/pages/Main/components/MainProfileModal/MainProfileModal.tsx
  src/pages/Main/components/MainProfileModal/ProfileAvatar.tsx
  src/pages/Main/components/MainProfileModal/ProfileBirthdayItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileColorItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileContainer.tsx
  src/pages/Main/components/MainProfileModal/ProfileMBTIItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileNameItem.tsx
  src/pages/Main/components/MainSolo.tsx
  src/pages/Main/components/index.ts
  src/pages/Main/context/MainContext.tsx
  src/pages/Main/context/ProfileModalContext.tsx
  src/pages/Main/context/index.ts
  src/pages/Main/hooks/index.ts
  src/pages/Main/hooks/useCreateCoupleCode.ts
  src/pages/Main/hooks/useEditCoupleProfile.ts
  src/pages/Main/hooks/useEditProfile.ts
  src/pages/Main/hooks/useGetCoupleProfile.ts
  src/pages/Main/hooks/useGetProfile.ts
  src/pages/Main/hooks/useMain.ts
  src/pages/Main/hooks/useProfileModal.ts
  src/router/Layout.tsx
  src/theme/avatar.ts
  src/theme/screens.ts
  src/types/couple.ts
  src/types/member.ts
Labels: ✨ Feat, 💄 Style, 🔨 Refactoring

#93 🚀 Build: emotion 관련 세팅
  src/components/common/MapFilterButton/MapFilterButton.stories.ts
  src/components/domain/Rating/Rating.stories.ts
  src/components/domain/TemperatureBar/TemperatureBar.stories.ts
  src/main.tsx
  src/pages/Calendar/components/CalendarMain.tsx
  src/pages/Login/Login.stories.tsx
  src/pages/Question/contexts/QuestionContext.tsx
  src/pages/QuestionCreate/contexts/QuestionCreateFormContext.tsx
  src/pages/QuestionCreate/hooks/useQuestionCreateForm.tsx
  tsconfig.json
Labels: 📝 Chore

#94 🔨 Refactor: 질문 페이지 api hooks 로직 수정
  src/pages/Question/Question.tsx
  src/pages/Question/contexts/QuestionContext.tsx
  src/pages/Question/hooks/useCreateTodayQuestion.ts
  src/pages/Question/hooks/useGetQuestion.ts
  src/pages/Question/hooks/usePatchAnswerQuestion.ts
  src/pages/Question/hooks/useQuestion.tsx
  src/pages/QuestionCreate/hooks/useCreateForm.ts
  src/pages/QuestionHistory/components/HistoryList/HistoryItem.tsx
  src/pages/QuestionHistory/components/HistoryList/HistoryList.tsx
  src/pages/QuestionHistory/hooks/useGetQuestionDetail.ts
  src/pages/QuestionHistory/hooks/useGetQuestions.ts
  src/types/question.ts
Labels: 🔨 Refactoring

#97 💄 Style: 사이드바 css 수정 (붕 뜨는 문제 및 arrow 아이콘 rotate 문제)
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
Labels: 💄 Style

#100 🔨 Refactor: 공통 컴포넌트 정리 및 폰트 사이즈 적용
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Img/Img.tsx
  src/components/common/Input/Input.tsx
  src/components/common/index.ts
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/pages/Calendar/components/CalendarMain.tsx
  src/pages/Login/components/LoginButtons.tsx
  src/pages/Main/components/MainModalButtons/MainModalButtons.tsx
  src/pages/Main/components/MainProfile/Profile.tsx
  src/theme/avatar.ts
  src/theme/btn.ts
  src/theme/font.ts
  src/theme/fontSize.ts
  src/theme/img.ts
  src/theme/index.ts
  src/theme/input.ts
  tailwind.config.js
Labels: 🔨 Refactoring

#103 🔨 Refactor: Question, QuestionCreate 리팩토링 작업
  src/components/domain/NavigationHeader/NavigationHeader.tsx
  src/pages/Question/Question.tsx
  src/pages/Question/components/QuestionChat/Chat.tsx
  src/pages/Question/components/QuestionChat/ChatItem.tsx
  src/pages/Question/components/QuestionChat/index.ts
  src/pages/Question/components/QuestionForm/Form.tsx
  src/pages/Question/components/QuestionForm/FormAnswerItem.tsx
  src/pages/Question/components/QuestionForm/FormAnswers.tsx
  src/pages/Question/components/QuestionForm/FormCustomLink.tsx
  src/pages/Question/components/QuestionForm/FormQuestionnaire.tsx
  src/pages/Question/components/QuestionForm/QuestionForm.tsx
  src/pages/Question/components/QuestionForm/QuestionFormLabel.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelect.tsx
  src/pages/Question/components/QuestionForm/QuestionFormSelectItem.tsx
  src/pages/Question/components/QuestionForm/index.ts
  src/pages/Question/components/QuestionHeader/index.ts
  src/pages/Question/components/index.ts
  src/pages/Question/contexts/QuestionContext.tsx
  src/pages/Question/hooks/index.ts
  src/pages/Question/hooks/usePatchAnswerQuestion.ts
  src/pages/Question/hooks/useQuestion.tsx
  src/pages/Question/hooks/useUpdateUserAnswer.ts
  src/pages/Question/hooks/useUserAnswer.ts
  src/pages/QuestionCreate/components/QuestionCreateForm/Form.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswer.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswerCard.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/index.ts
  src/pages/QuestionCreate/components/QuestionCreateHeader/QuestionCreateHeader.tsx
  src/pages/QuestionCreate/components/index.ts
  src/pages/QuestionCreate/contexts/QuestionCreateFormContext.tsx
  src/pages/QuestionCreate/hooks/index.ts
  src/pages/QuestionCreate/hooks/useCreateForm.ts
  src/pages/QuestionCreate/hooks/useQuestionCreateForm.tsx
  src/pages/QuestionHistory/QuestionHistory.tsx
  src/pages/QuestionHistory/components/HistoryHeader/HistoryHeader.tsx
  src/pages/QuestionHistory/components/HistoryList/HistoryItem.tsx
  src/pages/QuestionHistory/components/HistoryList/index.ts
  src/pages/QuestionHistory/components/index.ts
Labels: 🚨 Fix, 🔨 Refactoring

#101 🔨 Refactor: 다이어리 페이지 리팩토링 (구조 및 css 변경 & Context 적용)
  src/components/domain/CategoryList/CategoryList.tsx
  src/pages/Diary/Diary.tsx
  src/pages/Diary/components/DiaryCommon/DiaryCategories.tsx
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
  src/pages/Diary/components/DiaryCommon/index.ts
  src/pages/Diary/components/DiaryContent/DiaryContent.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentDate.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentDetail.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentEditButton.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentHeader.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentImgs.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentRating.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentText.tsx
  src/pages/Diary/components/DiaryContent/DiaryImgsCarousel.tsx
  src/pages/Diary/components/DiaryContent/DiaryImgsUpload.tsx
  src/pages/Diary/components/DiaryContentLists/DiaryContentLists.tsx
  src/pages/Diary/components/DiaryContentLists/DiaryItems.tsx
  src/pages/Diary/components/DiaryContentLists/index.ts
  src/pages/Diary/components/DiaryMain/DiaryMain.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecords.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsHeader.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchBar.tsx
  src/pages/Diary/components/DiarySpot/DiaryListArea.tsx
  src/pages/Diary/components/DiarySpot/DiaryNotContent.tsx
  src/pages/Diary/components/DiarySpot/DiarySpot.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotHeader.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreview.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreviews.tsx
  src/pages/Diary/components/DiarySpot/index.ts
  src/pages/Diary/contexts/DiaryContentContext.tsx
  src/pages/Diary/contexts/DiaryImgsContext.tsx
  src/pages/Diary/contexts/DiaryMainContext.tsx
  src/pages/Diary/contexts/DiarySideBarContext.tsx
  src/pages/Diary/contexts/DiarySpotContent.tsx
Labels: 🔨 Refactoring

#102 🔨 Refactor: 메인 페이지 리팩토링
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainContent/InviteContainer.tsx
  src/pages/Main/components/MainContent/PreviewDiary.tsx
  src/pages/Main/components/MainContent/index.ts
  src/pages/Main/components/MainDdayModal/MainDdayModal.tsx
  src/pages/Main/components/MainDdayModal/index.ts
  src/pages/Main/components/MainInviteModal/MainInviteModal.tsx
  src/pages/Main/components/MainInviteModal/index.ts
  src/pages/Main/components/MainModalButtons/MainModalButtons.tsx
  src/pages/Main/components/MainProfile/CoupleProfile.tsx
  src/pages/Main/components/MainProfile/MainProfile.tsx
  src/pages/Main/components/MainProfile/Profile.tsx
  src/pages/Main/components/MainProfile/SoloProfile.tsx
  src/pages/Main/components/MainProfile/index.ts
  src/pages/Main/components/MainProfileModal/MBTIButton.tsx
  src/pages/Main/components/MainProfileModal/MainProfileModal.tsx
  src/pages/Main/components/MainProfileModal/ProfileAvatar.tsx
  src/pages/Main/components/MainProfileModal/ProfileBirthdayItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileColorItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileContainer.tsx
  src/pages/Main/components/MainProfileModal/ProfileMBTIItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileNameItem.tsx
  src/pages/Main/components/MainProfileModal/index.ts
  src/pages/Main/components/index.ts
  src/pages/Main/context/MainContext.tsx
  src/pages/Main/context/ProfileModalContext.tsx
  src/pages/Main/contexts/DdayModalContext.tsx
  src/pages/Main/contexts/MainContext.tsx
  src/pages/Main/contexts/ProfileContext.tsx
  src/pages/Main/contexts/ProfileModalContext.tsx
  src/pages/Main/contexts/index.ts
  src/pages/Main/hooks/index.ts
  src/pages/Main/hooks/useDdayModal.ts
  src/pages/Main/hooks/useEditProfile.ts
  src/pages/Main/hooks/useGetCoupleProfile.ts
  src/pages/Main/hooks/useGetProfile.ts
  src/pages/Main/hooks/useMain.ts
  src/pages/Main/hooks/useProfile.ts
  src/pages/Main/hooks/useProfileModal.ts
  src/pages/Main/index.ts
  src/pages/index.ts
  src/types/couple.ts
  src/types/member.ts
Labels: 🔨 Refactoring

#111 ✨ Feat: Login & Proxy 추가
  .gitignore
  src/api/apiClient.ts
  src/pages/Login/components/LoginButtons.tsx
  src/pages/Login/components/LoginTitle.tsx
  src/router/paths.ts
  src/theme/fontSize.ts
  vite.config.ts
Labels: ✨ Feat

#112 ✨ Feat: 다이어리 초기 진입 페이지 개발
  index.html
  src/assets/icons/currentMarker.svg
  src/assets/icons/index.ts
  src/assets/icons/mapMarkerGone.svg
  src/assets/icons/selectCoupleBtn.svg
  src/assets/icons/selectCurrentBtn.svg
  src/assets/icons/selectGoneBtn.svg
  src/assets/icons/selectNotBtn.svg
  src/pages/Diary/Diary.tsx
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentText.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecords.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchBar.tsx
  src/pages/Diary/components/DiaryMap/DiaryCustomInfo.tsx
  src/pages/Diary/components/DiaryMap/DiaryMap.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapButtons.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapMarker.tsx
  src/pages/Diary/components/DiaryMap/index.ts
  src/pages/Diary/components/DiarySpot/DiarySpotHeader.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/contexts/DiaryMapContext.tsx
  src/pages/Diary/contexts/DiarySideBarContext.tsx
  src/pages/Diary/hooks/useCurrentLocation.ts
  src/pages/Diary/hooks/useGetDiarys.ts
  src/pages/Diary/hooks/useHandleMarker.ts
  src/pages/Diary/hooks/useInfoToggle.ts
  src/pages/Diary/hooks/useInputRef.ts
  src/pages/Diary/hooks/useSearchLocation.ts
  src/pages/Diary/hooks/useSideBar.ts
  src/types/index.ts
  src/types/map.ts
Labels: ✨ Feat

#110 ✨ Feat: 질문 기록 페이지 무한 스크롤 적용
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/index.ts
  src/hooks/useCheckTokenParams.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useObserve.ts
  src/pages/Question/components/QuestionChat/ChatItem.tsx
  src/pages/Question/components/QuestionForm/FormAnswers.tsx
  src/pages/Question/contexts/QuestionContext.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswerInput.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormQuestion.tsx
  src/pages/QuestionCreate/hooks/index.ts
  src/pages/QuestionCreate/hooks/useFormAnswerInput.ts
  src/pages/QuestionCreate/hooks/useQuestionCreateForm.tsx
  src/pages/QuestionHistory/components/QuestionHistoryList/HistoryItem.tsx
  src/pages/QuestionHistory/components/QuestionHistoryList/HistoryItemContent.tsx
  src/pages/QuestionHistory/components/QuestionHistoryList/HistoryList.tsx
  src/pages/QuestionHistory/hooks/useHistoryItem.ts
  src/pages/QuestionHistory/hooks/useHistoryList.ts
  src/services/question/useGetQuestionDetail.ts
  src/services/question/useGetQuestionHistory.ts
  src/types/question.ts
Labels: 🚨 Fix, ✨ Feat

#128 ✨ Feat: Calendar 페이지 기능 추가
  src/assets/icons/index.ts
  src/assets/icons/trash.svg
  src/components/common/Loading/Loading.tsx
  src/components/domain/ScheduleItem/ScheduleItem.tsx
  src/constants/index.ts
  src/constants/scheduleColors.ts
  src/hooks/useCheckTokenParams.ts
  src/hooks/useLocalStorage.ts
  src/pages/Calendar/components/CalendarMain/CalendarMain.tsx
  src/pages/Calendar/components/CalendarMain/StyledCalendar.ts
  src/pages/Calendar/components/CalendarSideBar/CalendarSideBar.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarDaySchedule.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/EditOwner.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/EditType.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarEditSchedule/SideBarEditSchedule.tsx
  src/pages/Calendar/contexts/CalendarContext.tsx
  src/pages/Calendar/contexts/CalendarSideBarContext.tsx
  src/pages/Calendar/utils/formatDate.ts
  src/pages/Main/components/MainContent/PreviewCalendar.tsx
  src/services/calendar/useCreateSchedule.ts
  src/services/calendar/useDeleteSchedule.ts
  src/services/calendar/useEditSchedule.ts
  src/services/calendar/useGetMonthSchedule.ts
  src/types/calendar.ts
  src/utils/getScheduleColor.ts
  src/utils/index.ts
Labels: ✨ Feat, 💄 Style, 🔨 Refactoring

#130 🚨 Fix: 카카오지도 인포윈도우 z-index 문제 수정
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/pages/Diary/components/DiaryMap/DiaryCustomInfo.tsx
  src/pages/Diary/contexts/DiaryMapContext.tsx
  src/pages/Diary/hooks/useCategorySearch.ts
  src/pages/Main/components/MainContent/PreviewDiary.tsx
  src/pages/Main/components/MainContent/PreviewItem.tsx
  src/pages/Main/components/MainContent/PreviewNoneItem.tsx
  src/pages/Main/components/MainContent/PreviewsContainer.tsx
Labels: 🚨 Fix

#132 🚨 Fix: 다이어리 문제 수정
  package-lock.json
  package.json
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
  src/pages/Diary/components/DiaryCommon/SideBarFallback.tsx
  src/pages/Diary/components/DiaryContent/DiaryContent.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiarySpot/DiaryListArea.tsx
  src/pages/Diary/components/DiarySpot/DiarySpot.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotHeader.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreview.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreviews.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/contexts/DiarySpotContent.tsx
  src/pages/Diary/contexts/DiarySpotContext.tsx
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/pages/Diary/hooks/useDiaryContext.ts
  src/pages/Diary/hooks/useDiarySpotContext.ts
  src/pages/Diary/hooks/useHandleMarker.ts
  src/services/diary/useGetSpotDiarys.ts
  src/types/diary.ts
Labels: 🚨 Fix

#133 🔨 Refactoring: DiayContext 수정
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentHeader.tsx
  src/pages/Diary/components/DiaryMain/DiaryMain.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecords.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsHeader.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchBar.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchResults.tsx
  src/pages/Diary/components/DiaryMap/DiaryMap.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapButtons.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapCategoryList.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapMarker.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotHeader.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/contexts/DiaryMapContext.tsx
  src/pages/Diary/hooks/Diary/useClickPreview.ts
  src/pages/Diary/hooks/Diary/useCurrentLocation.ts
  src/pages/Diary/hooks/Diary/useDiary.ts
  src/pages/Diary/hooks/Diary/useDiaryCategories.ts
  src/pages/Diary/hooks/Diary/useDiarytoMarker.ts
  src/pages/Diary/hooks/Diary/useFilterMarker.ts
  src/pages/Diary/hooks/Diary/useHandleMarker.ts
  src/pages/Diary/hooks/Diary/useInfoToggle.ts
  src/pages/Diary/hooks/Diary/useInputRef.ts
  src/pages/Diary/hooks/Diary/useMapCategory.ts
  src/pages/Diary/hooks/Diary/useMapLocation.ts
  src/pages/Diary/hooks/Diary/useSelectSortMethod.ts
  src/pages/Diary/hooks/Diary/useSideBar.ts
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/pages/Diary/hooks/DiaryMap/useDiaryMap.ts
  src/pages/Diary/hooks/useCategorySearch.ts
  src/pages/Diary/hooks/useCurrentLocation.ts
  src/pages/Diary/hooks/useHandleMarker.ts
  src/pages/Diary/hooks/useInfo.ts
  src/pages/Diary/hooks/useInfoToggle.ts
  src/pages/Diary/hooks/useMapCategory.ts
  src/pages/Diary/hooks/useMarkers.ts
  src/pages/Diary/hooks/useSearchLocation.ts
  src/pages/Diary/hooks/useSelectCategory.ts
  src/pages/Diary/hooks/useSelectSortMethod.ts
  src/pages/Diary/hooks/useSideBar.ts
  src/services/diary/useGetDiarys.ts
Labels: 🔨 Refactoring

#137 ✨ Feat: Diary 다중 삭제 연동 및 검색 로직 수정
  src/api/apiClient.ts
  src/hooks/useLogin.ts
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapMarker.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreview.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreviews.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/contexts/DiarySpotContext.tsx
  src/pages/Diary/hooks/Diary/useDiarytoMarker.ts
  src/pages/Diary/hooks/Diary/useFilterMarker.ts
  src/pages/Diary/hooks/Diary/useMapCategory.ts
  src/pages/Diary/hooks/Diary/useMapLocation.ts
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/router/PrivateRouter.tsx
  src/services/diary/useCreateDiaryDetail.ts
  src/services/diary/useDeleteDiaryDetail.ts
  src/services/diary/useGetDiarys.ts
Labels: ✨ Feat

#138 ✨ Feat: 다이어리 고도화
  src/components/common/CategoryButton/CategoryButton.tsx
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/pages/Diary/Diary.tsx
  src/pages/Diary/DiaryLoading.tsx
  src/pages/Diary/components/DiaryCommon/DiarySideBar.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentEditButton.tsx
  src/pages/Diary/components/DiaryContent/DiaryContentHeader.tsx
  src/pages/Diary/components/DiaryContent/DiaryImgsCarousel.tsx
  src/pages/Diary/components/DiaryContent/DiaryImgsUpload.tsx
  src/pages/Diary/components/DiaryMain/DiaryMain.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecords.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsHeader.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchBar.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchResults.tsx
  src/pages/Diary/components/DiaryMap/DiaryMap.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapButtons.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapCategoryList.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapMarker.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotHeader.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreview.tsx
  src/pages/Diary/contexts/DiaryContent/DiaryContentContext.tsx
  src/pages/Diary/contexts/DiaryContent/ReadContext.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/contexts/DiaryMainContext.tsx
  src/pages/Diary/contexts/DiaryMapContext.tsx
  src/pages/Diary/contexts/DiarySpotContext.tsx
  src/pages/Diary/hooks/Diary/useDiary.ts
  src/pages/Diary/hooks/Diary/useDiaryCategories.ts
  src/pages/Diary/hooks/Diary/useDiaryContext.ts
  src/pages/Diary/hooks/Diary/useDiarytoMarker.ts
  src/pages/Diary/hooks/Diary/useFilterMarker.ts
  src/pages/Diary/hooks/Diary/useMapCategory.ts
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/pages/Diary/hooks/DiaryMain/useDiaryMainContext.ts
  src/pages/Diary/hooks/DiaryMain/useDiaryMainObserver.ts
  src/pages/Main/components/MainContent/MainContent.tsx
  src/pages/Main/components/MainContent/MainContentErrorBoundary.tsx
  src/pages/Main/contexts/MainContentContext.tsx
  src/services/diary/useCreateDiaryDetail.ts
  src/services/diary/useEditDiaryDetail.ts
  src/services/diary/useGetDiarys.ts
  src/types/diary.ts
Labels: ✨ Feat

#139 🚨Fix: 무한 스크롤 에러 수정
  src/pages/Diary/Diary.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapMarker.tsx
  src/pages/Diary/contexts/DiaryContent/DiaryContentContext.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/contexts/DiaryMainContext.tsx
  src/pages/Diary/hooks/Diary/useDiarytoMarker.ts
  src/pages/Diary/hooks/Diary/useFilterMarker.ts
  src/pages/Diary/hooks/DiaryMain/useDiaryMainObserver.ts
Labels: 🚨 Fix

#140 🔨 Refactor: 다이어리 일부 리팩토링
  src/pages/Diary/Diary.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotPreview.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/hooks/Diary/useClickPreview.ts
  src/pages/Diary/hooks/Diary/useFilterMarker.ts
  src/pages/Diary/hooks/Diary/useMapCategory.ts
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/services/diary/useDeleteDiaryDetail.ts
Labels: 🔨 Refactoring

#142 🔨 Refactor: 다이어리 기능 리팩토링
  src/pages/Diary/components/DiaryMain/DiaryRecordsHeader.tsx
  src/pages/Diary/components/DiaryMain/DiaryRecordsPreviews.tsx
  src/pages/Diary/components/DiaryMain/DiarySearchResults.tsx
  src/pages/Diary/components/DiaryMain/SearchResultsItems.tsx
  src/pages/Diary/components/DiaryMap/DiaryMapButtons.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/contexts/DiaryMainContext.tsx
  src/pages/Diary/contexts/DiarySpotContext.tsx
  src/pages/Diary/hooks/Diary/useCurrentLocation.ts
  src/pages/Diary/hooks/Diary/useFilterMarker.ts
  src/pages/Diary/hooks/Diary/useMapCategory.ts
  src/pages/Diary/hooks/Diary/useMapLocation.ts
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/services/diary/useCreateDiaryDetail.ts
  src/services/diary/useDeleteDiaryDetail.ts
  src/services/diary/useGetDiaryDetail.ts
  src/services/diary/useGetDiarys.ts
  src/services/diary/useGetSpotDiarys.ts
Labels: 🔨 Refactoring

#135 💄 Style: Main, Question 페이지 디자인 수정
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/components/domain/NavigationHeader/NavigationHeader.tsx
  src/components/domain/ScheduleItem/ScheduleItem.tsx
  src/pages/Calendar/components/CalendarSideBar/SideBarDaySchedule.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainContent/PreviewCalendar.tsx
  src/pages/Main/components/MainContent/PreviewItem.tsx
  src/pages/Main/components/MainContent/PreviewNoneItem.tsx
  src/pages/Main/components/MainContent/PreviewQuestion.tsx
  src/pages/Main/components/MainContent/PreviewsContainer.tsx
  src/pages/Main/components/MainModalButtons/MainModalButtons.tsx
  src/pages/Main/components/MainProfile/CoupleProfile.tsx
  src/pages/Main/components/MainProfile/Profile.tsx
  src/pages/Main/contexts/MainContentContext.tsx
  src/pages/Question/Question.tsx
  src/pages/Question/components/QuestionChat/ChatItem.tsx
  src/pages/Question/components/QuestionForm/FormAnswerItem.tsx
  src/pages/Question/components/QuestionForm/FormAnswers.tsx
  src/pages/Question/components/QuestionForm/FormCustomLink.tsx
  src/pages/Question/components/QuestionForm/FormQuestionnaire.tsx
  src/pages/Question/components/QuestionHeader/QuestionHeader.tsx
  src/pages/QuestionCreate/QuestionCreate.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/Form.tsx
  src/pages/QuestionCreate/components/QuestionCreateForm/FormAnswerInput.tsx
  src/pages/QuestionCreate/components/QuestionCreateHeader/QuestionCreateHeader.tsx
  src/pages/QuestionCreate/components/index.ts
  src/pages/QuestionHistory/QuestionHistory.tsx
  src/pages/QuestionHistory/components/QuestionHistoryHeader/HistoryHeader.tsx
  src/pages/QuestionHistory/components/QuestionHistoryList/HistoryItem.tsx
  src/pages/QuestionHistory/components/QuestionHistoryList/HistoryList.tsx
  src/pages/QuestionHistory/components/index.ts
Labels: 💄 Style

#125 ✨ Feat: SettingPage 추가
  src/pages/Setting/Setting.tsx
  src/pages/Setting/components/SettingContent/ContentItem.tsx
  src/pages/Setting/components/SettingContent/SettingContent.tsx
  src/pages/Setting/components/SettingTab.tsx
  src/pages/Setting/components/index.ts
  src/pages/Setting/constants/index.ts
  src/pages/Setting/constants/settingTab.ts
  src/pages/Setting/contexts/SettingContext.tsx
  src/pages/Setting/contexts/index.ts
  src/pages/Setting/hooks/index.ts
  src/pages/Setting/hooks/useSetting.ts
  src/pages/index.ts
  src/router/router.tsx
Labels: ✨ Feat

#143 ✨ Feat: Login 적용
  src/api/apiClient.ts
  src/components/domain/Footer/Footer.tsx
  src/components/domain/Footer/FooterItem.tsx
  src/components/domain/TemperatureBar/TemperatureBar.tsx
  src/constants/index.ts
  src/constants/tokenKeys.ts
  src/hooks/index.ts
  src/hooks/useLogin.ts
  src/pages/Login/Login.tsx
  src/pages/Login/components/LoginButtons.tsx
  src/pages/Login/components/LoginTitle.tsx
  src/router/PrivateRouter.tsx
  src/router/paths.ts
  src/services/couple/index.ts
  src/services/couple/useGetTemperature.ts
  src/utils/localStorage.ts
Labels: ✨ Feat

#146 🔨 Refactoring: 메인 페이지 디자인 수정 및 캘린더 수정
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Img/Img.tsx
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/components/domain/ScheduleItem/ScheduleItem.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/MainContentErrorBoundary.tsx
  src/pages/Main/components/MainContent/MainContent.tsx
  src/pages/Main/components/MainContent/PreviewCalendar.tsx
  src/pages/Main/components/MainContent/PreviewDiary.tsx
  src/pages/Main/components/MainContent/PreviewQuestion.tsx
  src/pages/Main/contexts/MainContentContext.tsx
  src/pages/Main/contexts/ProfileContext.tsx
  src/services/calendar/useCreateSchedule.ts
  src/services/calendar/useDeleteSchedule.ts
Labels: 🔨 Refactoring

#148 🔨 Refactor: 다이어리 목록 리스트 클릭시 마커 안보이는 문제 수정
  src/pages/Diary/components/DiaryMap/DiaryMapMarker.tsx
  src/pages/Diary/contexts/DiaryContext.tsx
  src/pages/Diary/hooks/Diary/useClickPreview.ts
  src/pages/Diary/hooks/Diary/useMapLocation.ts
Labels: 🔨 Refactoring

#147 ✨Feat: 질문 페이지 고도화 작업
  src/components/domain/ScheduleItem/ScheduleItem.tsx
  src/pages/Diary/components/DiarySpot/DiaryListArea.tsx
  src/pages/Diary/components/DiarySpot/DiarySpotHeader.tsx
  src/pages/Diary/hooks/DiaryContent/useDiaryContent.ts
  src/pages/Main/components/MainContent/PreviewDiary.tsx
  src/pages/Main/contexts/MainContentContext.tsx
  src/pages/Question/Question.tsx
  src/pages/Question/components/QuestionChat/Chat.tsx
  src/pages/Question/components/QuestionErrorFallback.tsx
  src/pages/Question/components/QuestionForm/Form.tsx
  src/pages/Question/components/QuestionForm/FormAnswers.tsx
  src/pages/Question/components/QuestionForm/FormQuestionnaire.tsx
  src/pages/Question/components/QuestionLoadingFallback.tsx
  src/pages/Question/contexts/QuestionContext.tsx
  src/pages/Question/hooks/useQuestion.tsx
  src/pages/Question/hooks/useQuestionContext.ts
  src/pages/Question/hooks/useUserAnswer.ts
  src/services/diary/useCreateDiaryDetail.ts
  src/services/diary/useDeleteDiaryDetail.ts
  src/services/question/useCreateForm.ts
  src/services/question/useGetQuestion.ts
  src/services/question/useGetQuestionDetail.ts
  src/services/question/useUpdateUserAnswer.ts
  src/types/question.ts
Labels: ✨ Feat
