Repository Lovely-4K/love-frontend, pull requests merged in 2023-10, with the labels that each got.

#2 ✨ Feat: DotTag 컴포넌트 추가
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/issue-템플릿.md
  .github/pull_request_template.md
  src/App.tsx
  src/components/common/DotTag.tsx
  src/components/common/DotTag/DotTag.stories.ts
  src/components/common/DotTag/DotTag.tsx
  src/components/common/DotTag/index.ts
  src/components/common/index.ts
  src/theme/components/common/Button.ts
  src/theme/components/common/DotTag.ts
  src/theme/components/index.ts
  src/theme/config.ts
  src/theme/index.ts
Labels: ✨ Feat

#7 ✨ Feat: Avatar 컴포넌트 추가
  src/components/common/CustomAvatar/CustomAvatar.stories.ts
  src/components/common/CustomAvatar/CustomAvatar.tsx
  src/components/common/CustomAvatar/index.ts
  src/components/common/index.ts
Labels: ✨ Feat

#13 ✨ Feat: 메시지 박스 컴포넌트 추가
  src/components/common/MessageBox/MessageBox.stories.ts
  src/components/common/MessageBox/MessageBox.tsx
  src/components/common/MessageBox/index.ts
  src/components/common/index.ts
Labels: ✨ Feat

#9 ✨ Feat: 온도바 컴포넌트 추가
  src/assets/icons/heart.svg
  src/components/common/TemperatureBar/TemperatureBar.stories.ts
  src/components/common/TemperatureBar/TemperatureBar.tsx
  src/components/common/TemperatureBar/index.ts
  src/components/common/index.ts
Labels: ✨ Feat

#18 ✨ Feat: Input 컴포넌트 구현
  src/components/common/CustomInput/CustomInput.stories.ts
  src/components/common/CustomInput/CustomInput.tsx
  src/components/common/CustomInput/index.ts
Labels: ✨ Feat

#12 ✨ Feat: CustomBox, Image 추가
  src/components/common/CustomBox/CustomBox.stories.ts
  src/components/common/CustomBox/CustomBox.tsx
  src/components/common/CustomBox/index.ts
  src/components/common/CustomImage/CustomImage.stories.ts
  src/components/common/CustomImage/CustomImage.tsx
  src/components/common/CustomImage/index.ts
  src/components/common/index.ts
Labels: ✨ Feat

#10 ✨ Feat: MapButton 추가
  .storybook/preview.ts
  src/assets/icons/heart.svg
  src/assets/icons/index.ts
  src/assets/icons/position.svg
  src/components/common/CustomAvatar/CustomAvatar.tsx
  src/components/common/DotTag/DotTag.stories.ts
  src/components/common/DotTag/DotTag.tsx
  src/components/common/MapFilterButton/MapFilterButton.stories.ts
  src/components/common/MapFilterButton/MapFilterButton.tsx
  src/components/common/MapFilterButton/index.ts
  src/components/common/MapPosButton/MapPosButton.stories.ts
  src/components/common/MapPosButton/MapPosButton.tsx
  src/components/common/MapPosButton/index.ts
  src/components/common/index.ts
Labels: ✨ Feat

#23 ✨ Feat: 버튼 스타일 지정
  src/theme/btn.ts
  src/theme/colors.ts
  tailwind.config.js
Labels: ✨ Feat

#22 ✨ Feat: Carousel 컴포넌트 추가
  src/components/domain/Carousel/Carousel.stories.ts
  src/components/domain/Carousel/Carousel.tsx
  src/components/domain/Carousel/index.ts
  src/components/domain/index.ts
Labels: ✨ Feat

#28 ✨ Feat: 평점 컴포넌트 추가
  src/components/domain/Rating/Rating.stories.ts
  src/components/domain/Rating/Rating.tsx
  src/components/domain/Rating/index.ts
  src/components/domain/index.ts
Labels: ✨ Feat

#29 ✨ Feat: input 컴포넌트 타입 추가
  src/theme/input.ts
  tailwind.config.js
Labels: ✨ Feat

#27 💄 Style: avatar 컴포넌트 theme 추가
  src/theme/avatar.ts
  tailwind.config.js
Labels: 💄 Style

#25 ✨ Feat: MapButton 컴포넌트 추가
  src/components/common/MapCurPosButton/MapCurPosButton.stories.tsx
  src/components/common/MapCurPosButton/MapCurPosButton.tsx
  src/components/common/MapCurPosButton/index.ts
  src/components/common/MapFilterButton/MapFilterButton.stories.ts
  src/components/common/MapFilterButton/MapFilterButton.tsx
  src/components/common/MapFilterButton/index.ts
  src/components/common/index.ts
  tailwind.config.js
Labels: ✨ Feat

#37 ✨ Feat | Domain 컴포넌트 Footer
  src/assets/icons/calendar.svg
  src/assets/icons/diary.svg
  src/assets/icons/home.svg
  src/components/domain/footer/Footer.stories.ts
  src/components/domain/footer/Footer.tsx
  src/components/domain/footer/FooterItem.tsx
  src/components/domain/footer/index.ts
  src/index.css
  src/theme/font.ts
  tailwind.config.js
Labels: ✨ Feat

#41 🔨 Refactoring: theme 폴더 정리하기
  src/theme/index.ts
  tailwind.config.js
Labels: 🔨 Refactoring

#34 ✨ Feat: CategoryList 컴포넌트 추가
  src/assets/icons/activity.svg
  src/assets/icons/cafe.svg
  src/assets/icons/etc.svg
  src/assets/icons/hotel.svg
  src/assets/icons/index.ts
  src/assets/icons/question.svg
  src/assets/icons/setting.svg
  src/components/common/CategoryButton/CategoryButton.stories.ts
  src/components/common/CategoryButton/CategoryButton.tsx
  src/components/common/CategoryButton/CategoryIcon.tsx
  src/components/common/CategoryButton/CategoryTypes.ts
  src/components/common/CategoryButton/index.ts
  src/components/common/index.ts
  src/components/domain/CategoryList/CategoryList.stories.ts
  src/components/domain/CategoryList/CategoryList.tsx
  src/components/domain/CategoryList/index.ts
Labels: ✨ Feat

#40 ✨ Feat : Router 기능 개발
  src/App.tsx
  src/components/domain/Footer/Footer.stories.ts
  src/components/domain/Footer/Footer.tsx
  src/components/domain/Footer/FooterItem.tsx
  src/components/domain/Footer/index.ts
  src/components/domain/footer/Footer.tsx
  src/components/domain/footer/FooterItem.tsx
  src/components/domain/index.ts
  src/router/Layout.tsx
  src/router/Router.tsx
Labels: ✨ Feat

#33 ✨ Feat: 온도바 컴포넌트 추가
  src/components/domain/TemperatureBar/TemperatureBar.stories.ts
  src/components/domain/TemperatureBar/TemperatureBar.tsx
  src/components/domain/TemperatureBar/index.ts
  src/components/domain/index.ts
Labels: ✨ Feat

#42 ✨ Feat: LoginPage 추가
  src/assets/images/couple.png
  src/assets/images/index.ts
  src/components/domain/Carousel/Carousel.tsx
  src/pages/Login/Login.stories.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/components/LoginContainer.tsx
  src/pages/Login/components/LoginTitle.tsx
  src/pages/Login/components/index.ts
  src/pages/Login/index.ts
  src/pages/index.ts
  src/theme/btn.ts
Labels: ✨ Feat

#46 ✨ Feat: 메인 페이지 컨텐츠 하단 작업(임시 완료)
  index.html
  package-lock.json
  src/components/domain/CalendarScheduleItem/CalendarScheduleItem.tsx
  src/components/domain/CalendarScheduleItem/index.ts
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/components/domain/DiaryPreviewItem/index.ts
  src/components/domain/index.ts
  src/index.css
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainPreviews/MainPreviewCalendar.tsx
  src/pages/Main/components/MainPreviews/MainPreviewDiary.tsx
  src/pages/Main/components/MainPreviews/MainPreviewItem.tsx
  src/pages/Main/components/MainPreviews/MainPreviewQuestion.tsx
  src/pages/Main/components/MainPreviews/MainPreviews.tsx
  src/pages/Main/components/MainPreviews/index.ts
  src/pages/Main/components/index.ts
  src/router/Layout.tsx
  src/router/Router.tsx
  src/theme/colors.ts
  src/theme/font.ts
  tailwind.config.js
Labels: ✨ Feat

#47 ✨ Feat: MainPage(커플) 상단, MainPage(솔로) UI 개발
  src/assets/icons/copyLink.svg
  src/assets/icons/index.ts
  src/pages/Main/components/MainCouple.tsx
  src/pages/Main/components/MainProfile.tsx
  src/pages/Main/components/MainSolo.tsx
  src/pages/Main/components/index.ts
Labels: ✨ Feat

#50 💄 Style: MainPage 레이아웃 합치기
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainCouple.tsx
  src/pages/Main/components/MainProfile/MainCoupleProfile.tsx
  src/pages/Main/components/MainProfile/MainProfile.tsx
  src/pages/Main/components/MainProfile/index.ts
  src/pages/Main/components/MainSolo.tsx
  src/pages/Main/components/index.ts
Labels: 💄 Style

#54 ✨ Feat: 커플 프로필 페이지 하단 구현
  src/components/domain/CalendarScheduleItem/CalendarScheduleItem.tsx
  src/components/domain/DiaryPreviewItem/DiaryPreviewItem.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainCouple.tsx
  src/pages/Main/components/MainPreviews/MainPreviewCalendar.tsx
  src/pages/Main/components/MainPreviews/MainPreviewDiary.tsx
  src/pages/Main/components/MainPreviews/MainPreviewItem.tsx
  src/pages/Main/components/MainPreviews/MainPreviewNoneItem.tsx
  src/pages/Main/components/MainPreviews/MainPreviewQuestion.tsx
  src/pages/Main/components/MainPreviews/MainPreviews.tsx
  src/pages/Main/components/MainProfile/MainProfile.tsx
  src/pages/Main/components/MainSolo.tsx
  src/pages/Main/components/index.ts
Labels: ✨ Feat

#51 💄 Style: LoginPage 스타일 변경
  src/pages/Login/Login.tsx
  src/pages/Login/components/LoginButtons.tsx
  src/pages/Login/components/LoginContainer.tsx
  src/pages/Login/components/LoginTitle.tsx
  src/pages/Login/components/index.ts
  src/pages/Main/components/index.ts
  src/theme/btn.ts
Labels: 💄 Style

#56 🔨 Refactor: profilemodal 수정
  src/constants/index.ts
  src/constants/personalColor.ts
  src/pages/Main/components/MainProfileModal/BirthdayDropdown.tsx
  src/pages/Main/components/MainProfileModal/MainProfileModal.tsx
  src/pages/Main/components/MainProfileModal/MbtiButton.tsx
  src/pages/Main/components/MainProfileModal/ProfileAvatar.tsx
  src/pages/Main/components/MainProfileModal/ProfileBirthdayItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileColorItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileContainer.tsx
  src/pages/Main/components/MainProfileModal/ProfileItemType.ts
  src/pages/Main/components/MainProfileModal/ProfileItemWrapper.tsx
  src/pages/Main/components/MainProfileModal/ProfileMbtiItem.tsx
  src/pages/Main/components/MainProfileModal/ProfileNameItem.tsx
  src/pages/Main/components/index.ts
  src/pages/Main/context/ProfileModalContext.tsx
  src/pages/Main/context/index.ts
  src/pages/Main/hooks/index.ts
  src/pages/Main/hooks/useProfileModal.ts
Labels: 🔨 Refactoring

#61 ✨ Feat: Footer에 온도바 추가
  src/assets/icons/question.svg
  src/assets/icons/setting.svg
  src/components/domain/CalendarScheduleItem/CalendarScheduleItem.tsx
  src/components/domain/Footer/Footer.tsx
  src/components/domain/Footer/FooterItem.tsx
  src/components/domain/TemperatureBar/TemperatureBar.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainCouple.tsx
  src/pages/Main/components/MainPreviews/MainPreviewItem.tsx
  src/pages/Main/components/MainPreviews/MainPreviews.tsx
  src/pages/Main/components/MainProfileModal/MBTIButton.tsx
  src/pages/Main/components/MainProfileModal/ProfileMBTIItem.tsx
  src/router/Layout.tsx
  src/router/Router.tsx
Labels: ✨ Feat
